$(document).ready(function(){
    $("#show1").click(function(){
        $("#1").show();
    });
    $("#show2").click(function(){
        $("#1").hide();
    });
    $("#show3").click(function(){
        $("#1").hide();
    });
    $("#show4").click(function(){
        $("#1").hide();
    });
    $("#show5").click(function(){
        $("#1").hide();
    });
    $("#show6").click(function(){
        $("#1").hide();
    });
    $("#show7").click(function(){
        $("#1").hide();
    });
    $("#show8").click(function(){
        $("#1").hide();
    });
    $("#show9").click(function(){
        $("#1").hide();
    });
    $("#show10").click(function(){
        $("#1").hide();
    });
    $("#show11").click(function(){
        $("#1").hide();
    });
});
$(document).ready(function(){
    $("#show2").click(function(){
        $("#2").show();
    });
    $("#show1").click(function(){
        $("#2").hide();
    });
    $("#show3").click(function(){
        $("#2").hide();
    });
    $("#show4").click(function(){
        $("#2").hide();
    });
    $("#show5").click(function(){
        $("#2").hide();
    });
    $("#show6").click(function(){
        $("#2").hide();
    });
    $("#show7").click(function(){
        $("#2").hide();
    });
    $("#show8").click(function(){
        $("#2").hide();
    });
    $("#show9").click(function(){
        $("#2").hide();
    });
    $("#show10").click(function(){
        $("#2").hide();
    });
    $("#show11").click(function(){
        $("#2").hide();
    });
});
$(document).ready(function(){
    $("#show3").click(function(){
        $("#3").show();
    });
    $("#show1").click(function(){
        $("#3").hide();
    });
    $("#show2").click(function(){
        $("#3").hide();
    });
    $("#show4").click(function(){
        $("#3").hide();
    });
    $("#show5").click(function(){
        $("#3").hide();
    });
    $("#show6").click(function(){
        $("#3").hide();
    });
    $("#show7").click(function(){
        $("#3").hide();
    });
    $("#show8").click(function(){
        $("#3").hide();
    });
    $("#show9").click(function(){
        $("#3").hide();
    });
    $("#show10").click(function(){
        $("#3").hide();
    });
    $("#show11").click(function(){
        $("#3").hide();
    });
});
$(document).ready(function(){
    $("#show4").click(function(){
        $("#4").show();
    });
    $("#show1").click(function(){
        $("#4").hide();
    });
    $("#show2").click(function(){
        $("#4").hide();
    });
    $("#show3").click(function(){
        $("#4").hide();
    });
    $("#show5").click(function(){
        $("#4").hide();
    });
    $("#show6").click(function(){
        $("#4").hide();
    });
    $("#show7").click(function(){
        $("#4").hide();
    });
    $("#show8").click(function(){
        $("#4").hide();
    });
    $("#show9").click(function(){
        $("#4").hide();
    });
    $("#show10").click(function(){
        $("#4").hide();
    });
    $("#show11").click(function(){
        $("#4").hide();
    });
});
$(document).ready(function(){
    $("#show5").click(function(){
        $("#5").show();
    });
    $("#show1").click(function(){
        $("#5").hide();
    });
    $("#show2").click(function(){
        $("#5").hide();
    });
    $("#show3").click(function(){
        $("#5").hide();
    });
    $("#show4").click(function(){
        $("#5").hide();
    });
    $("#show6").click(function(){
        $("#5").hide();
    });
    $("#show7").click(function(){
        $("#5").hide();
    });
    $("#show8").click(function(){
        $("#5").hide();
    });
    $("#show9").click(function(){
        $("#5").hide();
    });
    $("#show10").click(function(){
        $("#5").hide();
    });
    $("#show11").click(function(){
        $("#5").hide();
    });
});
$(document).ready(function(){
    $("#show6").click(function(){
        $("#6").show();
    });
    $("#show1").click(function(){
        $("#6").hide();
    });
    $("#show2").click(function(){
        $("#6").hide();
    });
    $("#show3").click(function(){
        $("#6").hide();
    });
    $("#show4").click(function(){
        $("#6").hide();
    });
    $("#show5").click(function(){
        $("#6").hide();
    });
    $("#show7").click(function(){
        $("#6").hide();
    });
    $("#show8").click(function(){
        $("#6").hide();
    });
    $("#show9").click(function(){
        $("#6").hide();
    });
    $("#show10").click(function(){
        $("#6").hide();
    });
    $("#show11").click(function(){
        $("#6").hide();
    });
});
$(document).ready(function(){
    $("#show7").click(function(){
        $("#7").show();
    });
    $("#show1").click(function(){
        $("#7").hide();
    });
    $("#show2").click(function(){
        $("#7").hide();
    });
    $("#show3").click(function(){
        $("#7").hide();
    });
    $("#show4").click(function(){
        $("#7").hide();
    });
    $("#show5").click(function(){
        $("#7").hide();
    });
    $("#show6").click(function(){
        $("#7").hide();
    });
    $("#show8").click(function(){
        $("#7").hide();
    });
    $("#show9").click(function(){
        $("#7").hide();
    });
    $("#show10").click(function(){
        $("#7").hide();
    });
    $("#show11").click(function(){
        $("#7").hide();
    });
});
$(document).ready(function(){
    $("#show8").click(function(){
        $("#8").show();
    });
    $("#show1").click(function(){
        $("#8").hide();
    });
    $("#show2").click(function(){
        $("#8").hide();
    });
    $("#show3").click(function(){
        $("#8").hide();
    });
    $("#show4").click(function(){
        $("#8").hide();
    });
    $("#show5").click(function(){
        $("#8").hide();
    });
    $("#show6").click(function(){
        $("#8").hide();
    });
    $("#show7").click(function(){
        $("#8").hide();
    });
    $("#show9").click(function(){
        $("#8").hide();
    });
    $("#show10").click(function(){
        $("#8").hide();
    });
    $("#show11").click(function(){
        $("#8").hide();
    });
});
$(document).ready(function(){
    $("#show9").click(function(){
        $("#9").show();
    });
    $("#show1").click(function(){
        $("#9").hide();
    });
    $("#show2").click(function(){
        $("#9").hide();
    });
    $("#show3").click(function(){
        $("#9").hide();
    });
    $("#show4").click(function(){
        $("#9").hide();
    });
    $("#show5").click(function(){
        $("#9").hide();
    });
    $("#show6").click(function(){
        $("#9").hide();
    });
    $("#show7").click(function(){
        $("#9").hide();
    });
    $("#show8").click(function(){
        $("#9").hide();
    });
    $("#show10").click(function(){
        $("#9").hide();
    });
    $("#show11").click(function(){
        $("#9").hide();
    });
});
$(document).ready(function(){
    $("#show10").click(function(){
        $("#10").show();
    });
    $("#show1").click(function(){
        $("#10").hide();
    });
    $("#show2").click(function(){
        $("#10").hide();
    });
    $("#show3").click(function(){
        $("#10").hide();
    });
    $("#show4").click(function(){
        $("#10").hide();
    });
    $("#show5").click(function(){
        $("#10").hide();
    });
    $("#show6").click(function(){
        $("#10").hide();
    });
    $("#show7").click(function(){
        $("#10").hide();
    });
    $("#show8").click(function(){
        $("#10").hide();
    });
    $("#show9").click(function(){
        $("#10").hide();
    });
    $("#show11").click(function(){
        $("#10").hide();
    });
});
$(document).ready(function(){
    $("#show11").click(function(){
        $("#11").show();
    });
    $("#show1").click(function(){
        $("#11").hide();
    });
    $("#show2").click(function(){
        $("#11").hide();
    });
    $("#show3").click(function(){
        $("#11").hide();
    });
    $("#show4").click(function(){
        $("#11").hide();
    });
    $("#show5").click(function(){
        $("#11").hide();
    });
    $("#show6").click(function(){
        $("#11").hide();
    });
    $("#show7").click(function(){
        $("#11").hide();
    });
    $("#show8").click(function(){
        $("#11").hide();
    });
    $("#show9").click(function(){
        $("#11").hide();
    });
    $("#show10").click(function(){
        $("#11").hide();
    });
});